name: cumuru-local-test

services:
  postgres:
    ports: !override
      []
  api:
    environment:
      TRUSTED_PROXY_CIDRS: 172.30.7.10/32
  web:
    ports: !override
      []
    networks:
      private:
        ipv4_address: 172.30.7.10

networks:
  private:
    ipam:
      config: !override
        - subnet: 172.30.7.0/24
